// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzNHR_PQaBYcTLy6a_qOtunmWowohEbCk',
    appId: '1:436921790012:web:f803383b7797d9d3f31d39',
    messagingSenderId: '436921790012',
    projectId: 'asistente-conversacional-bdebb',
    authDomain: 'asistente-conversacional-bdebb.firebaseapp.com',
    storageBucket: 'asistente-conversacional-bdebb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIdX68KX73xwomv83XAv5WEqgMLjqn_oo',
    appId: '1:436921790012:android:d6f54cf012accacdf31d39',
    messagingSenderId: '436921790012',
    projectId: 'asistente-conversacional-bdebb',
    storageBucket: 'asistente-conversacional-bdebb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFRuw0zOFmihXm3qLnJlS2yfwy_jcp0V0',
    appId: '1:436921790012:ios:5b077efa66c166d5f31d39',
    messagingSenderId: '436921790012',
    projectId: 'asistente-conversacional-bdebb',
    storageBucket: 'asistente-conversacional-bdebb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFRuw0zOFmihXm3qLnJlS2yfwy_jcp0V0',
    appId: '1:436921790012:ios:5b077efa66c166d5f31d39',
    messagingSenderId: '436921790012',
    projectId: 'asistente-conversacional-bdebb',
    storageBucket: 'asistente-conversacional-bdebb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzNHR_PQaBYcTLy6a_qOtunmWowohEbCk',
    appId: '1:436921790012:web:5af23e630c56e845f31d39',
    messagingSenderId: '436921790012',
    projectId: 'asistente-conversacional-bdebb',
    authDomain: 'asistente-conversacional-bdebb.firebaseapp.com',
    storageBucket: 'asistente-conversacional-bdebb.firebasestorage.app',
  );
}
